// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC5LWzdcdRGzfPsuPr8VhBL7_BD2EY9Fw',
    appId: '1:392276335159:web:38242fa01a55b053073db2',
    messagingSenderId: '392276335159',
    projectId: 'live5882',
    authDomain: 'live5882.firebaseapp.com',
    storageBucket: 'live5882.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-tOBBEiMgjcOh7SHMOFgfkwXMLEkp1uI',
    appId: '1:392276335159:android:e2db7a72d9ca36c2073db2',
    messagingSenderId: '392276335159',
    projectId: 'live5882',
    storageBucket: 'live5882.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKMjJnS8hzBSg8n89897LpRtMU_3YQe00',
    appId: '1:392276335159:ios:6de5a80aad75e56f073db2',
    messagingSenderId: '392276335159',
    projectId: 'live5882',
    storageBucket: 'live5882.appspot.com',
    iosClientId: '392276335159-6vvs3tstjtosmpjpu0jmfma54fc1icv6.apps.googleusercontent.com',
    iosBundleId: 'com.maciejsulikowski.live',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKMjJnS8hzBSg8n89897LpRtMU_3YQe00',
    appId: '1:392276335159:ios:6de5a80aad75e56f073db2',
    messagingSenderId: '392276335159',
    projectId: 'live5882',
    storageBucket: 'live5882.appspot.com',
    iosClientId: '392276335159-6vvs3tstjtosmpjpu0jmfma54fc1icv6.apps.googleusercontent.com',
    iosBundleId: 'com.maciejsulikowski.live',
  );
}
